from Tkinter import*
import ttk
def fx():
    root5=Tk()
    root5.title('Attendance record')
    Frame1=Frame(root5,width=1000,height=100,bd=8,relief='raise')
    Frame1.grid(row=0,column=0,sticky=W)
    Frame2=Frame(root5,width=1000,height=550,bd=8,relief='raise')
    Frame2.grid(row=1,column=0,sticky=W)
    v1=StringVar()
    v2=StringVar()
    v3=StringVar()
    v4=StringVar()
    v5=StringVar()
    v6=StringVar()
    v7=StringVar()
    v8=StringVar()
    v9=StringVar()
    v10=StringVar()
    v11=StringVar()

    #
    lblNo=Label(Frame1,font=('arial',10),text='SNO.',bg='white')
    lblNo.grid(row=0,column=0,sticky=W)
    lblStudentName=Label(Frame1,font=('arial',10),text='Daily Wage Labour Name',bd=12,bg='purple')
    lblStudentName.grid(row=0,column=1,sticky=W)
    lblCourseName=Label(Frame1,font=('arial',10),text='JOB',bd=12,bg='pink')
    lblCourseName.grid(row=0,column=2,sticky=W)
    box=ttk.Combobox(Frame1,textvariable=v1,state='readonly')
    box['values']=('Daily Wage Labour','Overtime','Mason','Diggers','Typist')
    box.grid(row=0,column=4)
    Button(Frame1,text='Fill',font='times 20 bold',width=12,height=1,bg='yellow').grid(row=0,column=5)
    Button(Frame1,text='Reset',font='times 20 bold',width=11,height=1,bg='light green').grid(row=0,column=6)
    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='1')
    lblNo.grid(row=0,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Drishti Singh',bd=12)
    lblStudentName.grid(row=0,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=0,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v2,state='readonly')
    box['values']=('p','A')
    box.grid(row=0,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=0,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=0,column=6)

    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='2',bd=16)
    lblNo.grid(row=1,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Shreya Singh',bd=12)
    lblStudentName.grid(row=1,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=1,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v3,state='readonly')
    box['values']=('P','A')
    box.grid(row=1,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=1,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=1,column=6)

    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='3',bd=16)
    lblNo.grid(row=2,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Anubhav Singh',bd=12)
    lblStudentName.grid(row=2,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=2,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v4,state='readonly')
    box['values']=('P','A')
    box.grid(row=2,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=2,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=2,column=6)

    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='4',bd=16)
    lblNo.grid(row=3,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Ankita Tripathi',bd=12)
    lblStudentName.grid(row=3,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=3,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v5,state='readonly')
    box['values']=('P','A')
    box.grid(row=3,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=3,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=3,column=6)
    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='5',bd=16)
    lblNo.grid(row=4,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Archana Singh',bd=12)
    lblStudentName.grid(row=4,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=4,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v6,state='readonly')
    box['values']=('P','A')
    box.grid(row=4,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=4,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=4,column=6)
    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='6',bd=16)
    lblNo.grid(row=5,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Deepa Rathore',bd=12)
    lblStudentName.grid(row=5,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=5,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v7,state='readonly')
    box['values']=('P','A')
    box.grid(row=5,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=5,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=5,column=6)

    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='7',bd=16)
    lblNo.grid(row=6,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Anjali Rajput',bd=12)
    lblStudentName.grid(row=6,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=6,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v8,state='readonly')
    box['values']=('P','A')
    box.grid(row=6,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=6,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=6,column=6)

    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='8',bd=16)
    lblNo.grid(row=7,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Shivangi Singh',bd=12)
    lblStudentName.grid(row=7,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=7,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v9,state='readonly')
    box['values']=('P','A')
    box.grid(row=7,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=7,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=7,column=6)
    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='9',bd=16)
    lblNo.grid(row=8,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Shiv Singh',bd=12)
    lblStudentName.grid(row=8,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=8,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v10,state='readonly')
    box['values']=('P','A')
    box.grid(row=8,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=8,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=8,column=6)
    #
    lblNo=Label(Frame2,font=('times 10 bold'),text='10',bd=16)
    lblNo.grid(row=9,column=0,sticky=W)
    lblStudentName=Label(Frame2,font=('times 10 bold'),text='Satyam Singh',bd=12)
    lblStudentName.grid(row=9,column=1,sticky=W)
    lblCourseName=Label(Frame2,font=('times 10 bold'),text='Daily Wage Labour',bd=12)
    lblCourseName.grid(row=9,column=2,sticky=W)
    box=ttk.Combobox(Frame2,textvariable=v11,state='readonly')
    box['values']=('P','A')
    box.grid(row=9,column=4)
    Button(Frame2,text='',font='times 20 bold',width=12,height=1).grid(row=9,column=5)
    Button(Frame2,text='',font='times 20 bold',width=11,height=1).grid(row=9,column=6)
    def save():
        Label(root5,text='Attendance Saved Successfully').pack()
    Button(Frame2,text='SAVE',font='times 20 bold',bg='blue',command=save).grid(row=10,column=6)
    def prev():
        root=Tk()
        
        Label(root,text='Date of previous day 1',font='times 20 italic').pack()
        e=Entry(root)
        e.pack()
        Label(root,text='Date of previous day 2',font='times 20 italic').pack()
        f=Entry(root)
        f.pack()
        Label(root,text='Date of previous day 3',font='times 20 italic').pack()
        g=Entry(root)
        g.pack()
        def wish():
            roota=Tk()
            Frame1=Frame(roota,width=1000,height=500,bd=8,relief='raise')
            Frame1.grid(row=0,column=0,sticky=W)
            lblNo=Label(Frame1,font=('arial',10),text='SNO.')
            lblNo.grid(row=0,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('arial',10),text='Student Name',bd=12,bg='purple')
            lblStudentName.grid(row=0,column=1,sticky=W)
            lblStudentName=Label(Frame1,font=('arial',10),text='Prev Day1',bd=12,bg='purple')
            lblStudentName.grid(row=0,column=2,sticky=W)
            lblStudentName=Label(Frame1,font=('arial',10),text='Prev Day2',bd=12,bg='purple')
            lblStudentName.grid(row=0,column=3,sticky=W)
            lblStudentName=Label(Frame1,font=('arial',10),text='Prev Day3',bd=12,bg='purple')
            lblStudentName.grid(row=0,column=4,sticky=W)
            #
            lblNo=Label(Frame1,font=('arial',10),text='1',bg='white')
            lblNo.grid(row=1,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('arial',10),text='Drishti Singh',bd=12)
            lblStudentName.grid(row=1,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=1,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=1,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=1,column=4,sticky=W)
            #
            lblNo=Label(Frame1,font=('times 10 bold'),text='2',bd=16)
            lblNo.grid(row=2,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('times 10 bold'),text='Shreya Singh',bd=12)
            lblStudentName.grid(row=2,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=2,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=2,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=2,column=4,sticky=W)
            #

            lblNo=Label(Frame1,font=('times 10 bold'),text='3',bd=16)
            lblNo.grid(row=3,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('times 10 bold'),text='Anubhav Singh',bd=12)
            lblStudentName.grid(row=3,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=3,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=3,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=3,column=4,sticky=W)
            #
            lblNo=Label(Frame1,font=('times 10 bold'),text='4',bd=16)
            lblNo.grid(row=4,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('times 10 bold'),text='Shreya Singh',bd=12)
            lblStudentName.grid(row=4,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=4,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=4,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=4,column=4,sticky=W)
            #
            lblNo=Label(Frame1,font=('times 10 bold'),text='5',bd=16)
            lblNo.grid(row=5,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('times 10 bold'),text='Shreya Singh',bd=12)
            lblStudentName.grid(row=5,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=5,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=5,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=5,column=4,sticky=W)
            #
            lblNo=Label(Frame1,font=('times 10 bold'),text='6',bd=16)
            lblNo.grid(row=6,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('times 10 bold'),text='Shreya Singh',bd=12)
            lblStudentName.grid(row=6,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=6,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=6,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=6,column=4,sticky=W)
            #
            lblNo=Label(Frame1,font=('times 10 bold'),text='7',bd=16)
            lblNo.grid(row=7,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('times 10 bold'),text='Shreya Singh',bd=12)
            lblStudentName.grid(row=7,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=7,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=7,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=7,column=4,sticky=W)
            #
            lblNo=Label(Frame1,font=('times 10 bold'),text='8',bd=16)
            lblNo.grid(row=8,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('times 10 bold'),text='Shreya Singh',bd=12)
            lblStudentName.grid(row=8,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=8,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=8,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=8,column=4,sticky=W)
            #
            lblNo=Label(Frame1,font=('times 10 bold'),text='9',bd=16)
            lblNo.grid(row=9,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('times 10 bold'),text='Shreya Singh',bd=12)
            lblStudentName.grid(row=9,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=9,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=9,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=9,column=4,sticky=W)
            #
            lblNo=Label(Frame1,font=('times 10 bold'),text='10',bd=16)
            lblNo.grid(row=10,column=0,sticky=W)
            lblStudentName=Label(Frame1,font=('times 10 bold'),text='Shreya Singh',bd=12)
            lblStudentName.grid(row=10,column=1,sticky=W)
            lblPrevDay1=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay1.grid(row=10,column=2,sticky=W)
            lblPrevDay2=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay2.grid(row=10,column=3,sticky=W)
            lblPrevDay3=Label(Frame1,font=('arial',10),text='P',bd=12,bg='pink')
            lblPrevDay3.grid(row=10,column=4,sticky=W)
            







            
        Button(root,text='SUBMIT',font='times 20 bold',bg='red',command=wish).pack()
    Button(Frame2,text='Previous attendance',font='times 20 bold',bg='red',command=prev).grid(row=10,column=2)
                    
    Button(Frame2,text='EXIT',font='times 20 bold',bg='red',command=root5.destroy).grid(row=10,column=4)
    root5.mainloop()
